default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: 12345

development:
  <<: *default
  database: octo_events_development

test:
  <<: *default
  database: octo_events_test

production:
  <<: *default
  database: octo_events_production
  username: octo_events
  password: <%= ENV["OCTO_EVENTS_DATABASE_PASSWORD"] %>
